runtime: nodejs20
entrypoint: 8080
service: default
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "22"
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5
