function C() { var choice = "Continuer#ReincarnationMalefique";var texting = `

<br/>c'est alors que cette quête..
<br/>je ne l'ai imagine, 
<br/>peut être...
<br/>que nos coeur lie, 
<br/>pouvait chanter, ou pas,
<br/>ça l'etait dejà,
<br/>et demain sera,
<br/>toujours un cas. 
<br/>Contre toute attente...
<br/>L'annee suivante,
<br/>notre volonte,
<br/>allez.
<br/>elle flechiera,
<br/>ou pas,
<br/>ça reviendra...
<br/>comme ça,
<br/>des fois...
<br/>sans avoir le choix,
<br/>on fait d'elle, 
<br/>un roi. 
<br/>Comme attire vers le ciel ! 
<br/>Sans qu'elle soit là..
<br/>focalise, 
<br/>on ne sait pas...
<br/>qu'on - se fait vrille ! 
<br/>Elle ne peut... 
<br/>elle ne peut...
<br/>être que belle ! 
<br/>ça pardonne pas;
<br/>à ce choix indescent 
<br/>inexistant 
<br/>presque sans voie, 
<br/>on voie.
<br/>Que celui qui te protège n'est pas là...
<br/>quand je pense à toi
<br/>si j'abrège, ça donne l'amour en une forme 
<br/>contraste 
<br/>sans une pomme revele dans l'orme 
<br/>si chaste...
<br/>elle nous allège cette sensation, 
<br/>communication,
<br/>paralèlle et belle... 
<br/>Comme si l'auteur devenait grelle 
<br/>cette annee là,
<br/>je n'ai pas pense à toi,
<br/>une seule fois. 
<br/>malgres l'obcenite,
<br/>de ce que j'ai fais...
<br/>tu as pense à moi,
<br/>comme autrefois...
<br/>En parlant d'un faux semblant, 
<br/>sincèrement.
<br/>
C'est Ainsi que la harpe se mis à chanter, et avoua sont vrai nom : "Tradictos".
<br/>
<br/>その時、このクエストは...
<br/>想像もしていなかった、多分...
<br/>私たちの心が縛られ、歌うことができた...
<br/>離れて...
<br/>あなたは理解していません、それはすでにありました、そして明日はいつもそうです。すべての可能性に対して...
<br/>翌年、私たちの意志は行きます。曲がるかどうかは別として、戻ってきます...
<br/>そのように、時々...
<br/>選択の余地なく、私たちは彼女を王にします。空に向かって描かれるように！彼女がそこにいなくても。
<br/>
<br/>焦点を合わせて、私たちは知りません...
<br/>私たち-ねじれる！彼女はできません...
<br/>彼女は美しいだけです！それは許しません。
<br/>この先天的な存在しないほとんど道のない選択に、私たちはあなたを保護する保護者がそこにいないことがわかります...
<br/>あなたを想うとき、短くすると、貞淑なニレにリンゴが出てこない、コントラストのない形で愛を与えてくれます...
<br/>それは、この並行した美しいコミュニケーションの感覚を和らげます...
<br/>偽物の似顔絵といえば、あたかもその年に作者がグレルになったようで、一度もあなたのことを考えたことはありませんでした。私がしたことの猥褻にもかかわらず...
<br/>あなたは前と同じように私のことを考えました...
<br/>心から。
<br/>
Le piano de Jasson composa alors :
<br/>
<br/>Sonotoki, kono kuesuto wa... 
<br/>Sōzō mo shite inakatta, tabun... 
<br/>Watashitachi no kokoro ga shibara re, utau koto ga dekita... 
<br/>Hanarete... 
<br/>Anata wa rikai shite imasen, sore wa sudeni arimashita, soshite ashita wa itsumo sōdesu. Subete no kanōsei ni taishite... 
<br/>Yokunen, watashitachi no ishi wa ikimasu. Magaru ka dō ka wa betsu to shite, modotte kimasu... 
<br/>Sonoyōni, tokidoki... 
<br/>Sentaku no yochi naku, watashitachi wa kanojo o ō ni shimasu. Sora ni mukatte egaka reru yō ni! Kanojo ga soko ni inakute mo.
<br/> 
<br/>Shōten o awasete, watashitachiha shirimasen... 
<br/>Watashitachi - nejireru! Kanojo wa dekimasen... 
<br/>Kanojo wa utsukushī dakedesu! Sore wa yurushimasen. Kono sententekina sonzaishinai hotondo michi no nai sentaku ni, watashitachi wa anata o hogo suru hogo-sha ga soko ni inai koto ga wakarimasu... 
<br/>Anata o omou toki, mijikaku suru to, teishukuna nire ni ringo ga detekonai, kontorasuto no nai katachi de ai o ataete kuremasu... 
<br/>Sore wa, kono heikō shita utsukushī komyunikēshon no kankaku o yawaragemasu... 
<br/>Nisemono no nigaoe to ieba, atakamo sono-nen ni sakusha ga gureru ni natta yō de, ichido mo anata no koto o kangaeta koto wa arimasendeshita. Watashi ga shita koto no waisetsu nimokakawarazu... 
<br/>Anata wa mae to onajiyōni watashinokoto o kangaemashita... 
<br/>Kokoro kara.


`;var ok = prog("page1-1", 1, (0.05*(texting.split("<br/>").length)));
var ajoue = ok.cadreGeometry("Cadre");
ajoue.changeCouleur("Cadre", "rgb(241,241,241)");
ajoue.plusItem("item1", 10, 100-(texting.split("<br/>").length*3), 80, -20+(texting.split("<br/>").length*3));
ajoue.changeCouleur("item1", "white"); 
ajoue.definirContour("item1", "mouse*030_rgba(50,50,50,1)_page1-1");
ajoue.changeOrdre("item1", "160");
var triag = "";
for (var a = 0; a < choice.split("*").length; a++) {
	triag += "<br/><button style='font-size: 38px; font-family: Helvetica;' onclick='suite(this, "+ '"' + choice.split("*")[a].split("#")[1] + '"' +")'>" + choice.split("*")[a].split("#")[0] + "</button>";
}
ajoue.utiliserHTML("item1", "<div style='font-size: 24px; font-family: Helvetica;' >" + texting + "</div><div style='position:fixed; bottom:0; right:50%'>" + triag + "</div>");
ok.ajouterGeometry("page1-1", ajoue.GeoString());
 var charge = ok.Activer(); 
charge.ChargerPage("DIV030", "page1-1", true, false); 
ok.autoZoom(false);
charge.autoRedimention(false, "page1");document.getElementById("DIV7").click();}